services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [ 5672, 15672 ]
  mercure:
    restart: unless-stopped
    image: dunglas/mercure:v0.10.4
    environment:

      CORS_ALLOWED_ORIGINS : "*"
      PUBLISH_ALLOWED_ORIGINS : "*"
      SERVER_NAME: ":80"
      JWT_KEY: "!ChangeMe!"
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'



      ALLOW_ANONYMOUS: 1

    ports:
      - 3000:80
